# Generated by Django 4.1.5 on 2023-03-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user_id_purposes",
                    models.CharField(
                        max_length=15, verbose_name="id пользователя телеграм"
                    ),
                ),
                (
                    "title_income",
                    models.CharField(
                        max_length=15, verbose_name="id пользователя телеграм"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Сумма")),
            ],
        ),
        migrations.CreateModel(
            name="Purposes",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user_id_purposes",
                    models.CharField(
                        max_length=15, verbose_name="id пользователя телеграм"
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=50,
                        verbose_name="Название раздела (Потребности|Инвестиции|Желания",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=50,
                        verbose_name="Название категории (еда,жилье,тс, итд",
                    ),
                ),
                (
                    "aliases",
                    models.CharField(
                        max_length=50,
                        verbose_name="Название алиаса (магазин:продукты:итд",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Сумма")),
                ("data", models.CharField(max_length=15, verbose_name="Дата")),
            ],
        ),
        migrations.CreateModel(
            name="User_verification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.CharField(
                        max_length=50, verbose_name="ID пользователя из телеграма"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        max_length=50, verbose_name="Имя пользователя из телеграма"
                    ),
                ),
                (
                    "activating_bot_goal",
                    models.CharField(
                        max_length=50,
                        verbose_name="Активация бота по (Цель): True - есть цель, False - нет цели",
                    ),
                ),
                (
                    "activating_bot_income",
                    models.CharField(
                        max_length=50,
                        verbose_name="Активация бота по (Доход): True - есть доход, False - нет дохода",
                    ),
                ),
            ],
        ),
    ]
