# Generated by Django 4.1.5 on 2023-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expenses_needs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user_id_purposes",
                    models.CharField(
                        max_length=15, verbose_name="id пользователя телеграм"
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=50,
                        verbose_name="Название раздела (Потребности|Инвестиции|Желания",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=50,
                        verbose_name="Название категории (еда,жилье,тс, итд",
                    ),
                ),
                (
                    "aliases",
                    models.CharField(
                        max_length=50,
                        verbose_name="Название алиаса (магазин:продукты:итд",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Сумма")),
                (
                    "quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество"
                    ),
                ),
                (
                    "data_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                ("raw_text", models.TextField(verbose_name="Полный текст сообщения")),
            ],
        ),
    ]
